version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_DATABASE: ecommerce
