CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    created  timestamp                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified timestamp                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email    VARCHAR(255)                            NOT NULL UNIQUE,
    password VARCHAR(255),
    role     VARCHAR(255)                            NOT NULL DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER')),
    status   boolean                                 NOT NULL DEFAULT TRUE
);

INSERT INTO users (email, password, role)
VALUES ('admin@mail.com', '$2a$10$.PFCwHn9rAckYkSRHew/v.kAnxhPa6FEBOU1TfabBgApyJ3DD9zmO', 'ADMIN');


CREATE TABLE IF NOT EXISTS customers
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    created  timestamp                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified timestamp                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name     VARCHAR(255)                            NOT NULL,
    surname  VARCHAR(255)                            NOT NULL,
    user_id  BIGINT                                  NOT NULL REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS product
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    created  timestamp                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified timestamp                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name     VARCHAR(255)                            NOT NULL,
    price    DECIMAL(10, 2)                          NOT NULL,
    stock    INT                                     NOT NULL
);